---
- name: Setup Dev Machine
  hosts: all
  roles:
    - { role: packages }
    # - { role: user, become: true }

- name: Setup Designate
  hosts: all
  roles:
    - { role: designate }
  tag: designate
