---
- name: Add emacs ppa
  become: true
  apt_repository: repo='ppa:ubuntu-elisp/ppa' state=present

- name: Add git ppa
  become: true
  apt_repository: repo='ppa:git-core/ppa' state=present

- name: Get up to date
  become: true
  apt: upgrade=yes

- name: Update our index
  become: true
  apt: name={{ item }} update_cache=yes
  with_items:
    - 'python-pip'
    - 'python-virtualenv'
    - 'python-mysqldb'
    - 'python-dev'
    - 'rabbitmq-server'
    - 'zookeeperd'
    - 'memcached'
    - 'mysql-server'
    - 'bind9'
    - 'libtool'
    - 'autoconf'
    - 'texinfo'
    - 'sbcl'
    - 'software-properties-common'
    - 'offlineimap'
    - 'libxapian-dev'
    - 'libglib2.0-dev'
    - 'libgmime-2.6-dev'
    - 'pkg-config'
    - 'keychain'
    - 'byobu'
    - 'emacs-snapshot'
    - 'git'

- name: Install docker
  become: True
  shell: wget -qO- https://get.docker.com/ | sh
